spring.application.name=bank-lab4

spring.datasource.url=jdbc:postgresql://localhost:5433/kpi_bank_db
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true